version: "3.1"
services:
  db:
    build: .
    ports:
      - "${PORT-6136}:6136"
    volumes:
      - ./data:/home/user/db
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_ACTIVATION_CODE: ${DB_ACTIVATION_CODE}